function [vert,ele,tnum] = extractMsh( msh )
% extractMsh: extract nodes and elements from struct variable 'msh'. 
% Struct variable 'msh' is generated by Gmsh.
%
% usage:
%   [vert,ele,tnum] = extractMsh( msh );
%
% output:
%   vert: Mesh nodes. It’s a Nn-by-2 matrix, where 
%         Nn is the number of nodes in the mesh. Each row of vert 
%         contains the x, y coordinates for that mesh node.
%     
%   ele: Mesh elements. 
%        For linear triangular elements, it s a Ne-by-3 matrix, where Ne 
%        is the number of elements in the mesh. 
%        Each row in ele contains the indices of the nodes for that mesh 
%        element.
%     
%   tnum: Label of phase. Ne-by-1 array, where Ne is the number of elements
%       tnum(j,1) = k; means the j-th element belongs to the k-th phase.
%
% Copyright (C) 2019-2025 by Jiexian Ma, mjx0799@gmail.com
% 
% Project website: https://github.com/mjx888/im2mesh
%

    if isfield(msh, 'TRIANGLES') && ~isfield(msh, 'QUADS')
	    vert = msh.POS(:,1:2);
	    ele = msh.TRIANGLES(:,1:end-1);
	    tnum = msh.TRIANGLES(:,end);
	    ele = fixOrdering( vert, ele );
    
    elseif isfield(msh, 'TRIANGLES6') && ~isfield(msh, 'QUADS9')
	    vert = msh.POS(:,1:2);
	    ele = msh.TRIANGLES6(:,1:end-1);
	    tnum = msh.TRIANGLES6(:,end);
	    ele = fixOrdering( vert, ele );
    
    elseif isfield(msh, 'QUADS')
        if isfield(msh, 'TRIANGLES')
            warning( '%s\n%s', ...
                'The input variable consists of both triangle and quadrilateral elements.', ...
                'Those triangle elements are neglected in the output of function extractMsh.' );
        end

	    vert = msh.POS(:,1:2);
	    ele = msh.QUADS(:,1:end-1);
	    tnum = msh.QUADS(:,end);
	    ele = fixOrdering( vert, ele );
    
    elseif isfield(msh, 'QUADS9')
        if isfield(msh, 'TRIANGLES6')
            warning( '%s\n%s', ...
                'The input variable consists of both triangle and quadrilateral elements.', ...
                'Those triangle elements are neglected in the output of function extractMsh.' );
        end
        
	    vert = msh.POS(:,1:2);
	    ele = msh.QUADS9(:,1:8);
	    tnum = msh.QUADS9(:,end);
	    ele = fixOrdering( vert, ele );
        
    else
        error('Unexpected case.');
    end

end
















