function [vert, ele, cmdout] = genTet( dockerCmd, mshFilePath )
% genTet: Generate tetrahedral mesh using fTetWild and load msh file
%
% This function generates a tetrahedral mesh by executing a specified
% Docker command (typically running fTetWild), measures the execution time,
% and then imports the resulting mesh (.msh file) into MATLAB.
%
% Inputs:
%   dockerCmd   - A string containing the Docker command to execute the 
%                 meshing tool (e.g., fTetWild).
%   mshFilePath - A string specifying the full file path to the .msh file 
%                 generated by the Docker process.
%
% Outputs:
%   vert        - A matrix containing the vertex coordinates of the imported mesh.
%   ele         - A matrix containing the element connectivity (tetrahedra) 
%                 of the imported mesh.
%   cmdout      - A string containing the real-time console output and logs 
%                 from the Docker execution.
%
% Copyright (C) 2019-2026 by Jiexian Ma, mjx0799@gmail.com
% Distributed under the terms of the GNU General Public License (version 3)
% 
% Project website: https://github.com/mjx888/im2mesh
%

    disp('//////////////// fTetWild via Docker ////////////////');
    
    % Start the timer
    tic;
    % Execute with '-echo' to see the real-time console output
    [status, cmdout] = system(dockerCmd, '-echo');
    
    % Stop the timer and store elapsed time
    executionTime = toc;
    % Check if it was successful
    if status == 0
        disp('//////////////// fTetWild Done! ////////////////');
        fprintf('//////////////// Time = %.2fs ////////////////\n', executionTime);
    else
        disp('//////////////// Error occurred ////////////////');
    end

    % import the .msh file into MATLAB
    [vert, ele] = readMsh( mshFilePath ); 
end